use_frameworks!

platform :ios, '10.0'

target 'MKGatewayUsbSeven_Example' do
  pod 'MKGatewayUsbSeven', :path => '../'

  target 'MKGatewayUsbSeven_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
